name: qr-biolink
services:
  qr-app:
    # 1. IMAGEN ACTUALIZADA
    image: sackboi/qr-saas:v3.2
    container_name: qr-biolink
    restart: unless-stopped
    
    # 2. Recursos
    deploy:
      resources:
        limits:
          memory: 512M
    
    # 3. Puertos
    ports:
      - target: 3001
        published: "3001"
        protocol: tcp
        
    # 4. Volúmenes
    volumes:
      - type: bind
        source: /DATA/AppData/qr-biolink/links.db
        target: /app/links.db
      - type: bind
        source: /DATA/AppData/qr-biolink/uploads
        target: /app/uploads
        
    # 5. Variables de Entorno
    environment:
      - NODE_ENV=production
      - JWT_SECRET=cambia_esta_clave_porfavor2334
      # IMPORTANTE: Cambia esto por tu dominio real (con https://)
      - PUBLIC_URL=url_publica

    # 6. Configuración visual interna de CasaOS
    x-casaos:
      ports:
        - container: "3001"
          description:
            en_US: Panel de Administración y Vista Pública
      volumes:
        - container: /app/links.db
          description:
            en_US: Base de datos SQLite
        - container: /app/uploads
          description:
            en_US: Carpeta persistente de Avatares (Fotos)

# 7. Metadatos de la Tienda CasaOS
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: sackboi
  category: Self-hosted
  description:
    en_US: >
      Micro-SaaS para generar páginas de Bio-Link y códigos QR dinámicos para negocios locales.
      Incluye panel de administración, temas personalizados y vista móvil optimizada (v3.0).
  developer: Koji
  icon: https://i.postimg.cc/qv5Djs0Z/treecify-icon.png
  main: qr-app
  port_map: "3001"
  scheme: http
  title:
    custom: Treecify v3
    en_us: Treecify v3